apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiremock
  labels:
    type: wiremock
spec:
  replicas: 1
  selector:
    matchLabels:
      type: wiremock
  template:
    metadata:
      labels:
        type: wiremock
    spec:
      containers:
      - name: wiremock
        image: rbillon59/wiremock-loadtest:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: wiremock-mapping
          mountPath: /home/wiremock/mappings
        - name: wiremock-file
          mountPath: /home/wiremock/__files
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1024m"
          limits:
            memory: "1024Mi"
            cpu: "1024m"
        livenessProbe:
          exec:
            command:
            - cat
            - /bin/cat
      volumes:
        - name: wiremock-mapping
          configMap:
            name: wiremock-mapping
        - name: wiremock-file
          configMap:
            name: wiremock-file
